name: Build Pawn Compiler

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7-a, armv8]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build for ${{ matrix.arch }}
        run: |
          docker buildx build --platform linux/${{ matrix.arch }} -t pawn-compiler:${{ matrix.arch }} .
