name: Build and Upload Artifacts

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64
          - armv7
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf cmake make

    - name: Setup build environment
      continue-on-error: true
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=../${{ matrix.arch }}-toolchain.cmake ../source/compiler

    - name: Build
      run: |
        cd build
        make

    - name: Copy out build artifacts
      run: |
        cp build/libpawnc.so libpawnc-${{ matrix.arch }}.so
        cp build/pawncc pawncc-${{ matrix.arch }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pawn-compiler-${{ matrix.arch }}
        path: |
          ./libpawnc-${{ matrix.arch }}.so
          ./pawncc-${{ matrix.arch }}
